---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/grup2857/public_html/new_sim
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp package-lock.json $DEPLOYPATH/
    - /bin/cp next.config.mjs $DEPLOYPATH/
    - /bin/cp public/ $DEPLOYPATH/public
    - /bin/cp .next/standalone/ $DEPLOYPATH/
    - /bin/cp .next/stati/ $DEPLOYPATH/.next/static
