---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/grup2857/public_html/new_sim
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp package-lock.json $DEPLOYPATH/
    - /bin/cp next.config.mjs $DEPLOYPATH/
    - /bin/cp -r public/ $DEPLOYPATH/public
    - /bin/cp -r .next/standalone/ $DEPLOYPATH/
    - /bin/cp -r .next/static/ $DEPLOYPATH/.next/static
