import {
  Course,
  IndicatorType,
  Lead,
  ListAction,
  Segment,
  TimeLine,
  Unit,
  UserType,
} from "@/types/general";

export type MockServer = {
  indicators: IndicatorType[];
  leads: Lead[];
  users: UserType[];
  segments: Segment[];
  unidades: Unit[];
  cursos: Course[];
  time_line: TimeLine[];
  listActionsIndicators: ListAction[];
  listActionsUsers: ListAction[];
  listActionsLeads: ListAction[];
  listActionsNewLeads: ListAction[];
  listActionsConfirmedLeads: ListAction[];
  listActionsWaitingConfirmationLeads: ListAction[];
  listActionsUnits: ListAction[];
  listActionsCourses: ListAction[];
  listActionsSegments: ListAction[];
};

export const mockServer: MockServer = {
  indicators: [
    {
      id: 1,
      name: "Argério",
      last_name: "Queiroz",
      city: "Macapá",
      link: "link",
      whatsapp: "234234234",
      user_at: "22/04/2023",
      document: "234234234",
      key_pix: "234234234",
      email: "teste@gmail.com",
      status: "status",
      leads: [
        {
          id: 6,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 7,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 8,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
      ],
    },
    {
      id: 2,
      name: "Argério Queiroz7",
      city: "Macapá",
      link: "link",
      whatsapp: "234234234",
      user_at: "22/04/2023",
      document: "234234234",
      key_pix: "234234234",
      email: "teste@gmail.com",
      status: "status",
      leads: [
        {
          id: 6,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 7,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 8,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
      ],
    },
    {
      id: 3,
      name: "Argério Queiroz6",
      city: "Macapá",
      link: "link",
      whatsapp: "234234234",
      user_at: "22/04/2023",
      document: "234234234",
      key_pix: "234234234",
      email: "teste@gmail.com",
      status: "status",
      leads: [
        {
          id: 6,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 7,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 8,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
      ],
    },
    {
      id: 4,
      name: "Argério Queiroz5",
      city: "Macapá",
      link: "link",
      whatsapp: "234234234",
      user_at: "22/04/2023",
      document: "234234234",
      key_pix: "234234234",
      email: "teste@gmail.com",
      status: "status",
      leads: [
        {
          id: 6,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 7,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 8,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
      ],
    },
    {
      id: 5,
      name: "Argério Queiroz4",
      city: "Macapá",
      link: "link",
      whatsapp: "234234234",
      user_at: "22/04/2023",
      document: "234234234",
      key_pix: "234234234",
      email: "teste@gmail.com",
      status: "status",
      leads: [
        {
          id: 6,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 7,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 8,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
      ],
    },
    {
      id: 6,
      name: "Argério Queiroz2",
      city: "Macapá",
      link: "link",
      whatsapp: "234234234",
      user_at: "22/04/2023",
      document: "234234234",
      key_pix: "234234234",
      email: "teste@gmail.com",
      status: "status",
      leads: [
        {
          id: 6,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 7,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 8,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
      ],
    },
    {
      id: 7,
      name: "Argério Queiroz3",
      city: "Macapá",
      link: "link",
      whatsapp: "234234234",
      user_at: "22/04/2023",
      document: "234234234",
      key_pix: "234234234",
      email: "teste@gmail.com",
      status: "status",
      leads: [
        {
          id: 6,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 7,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
        {
          id: 8,
          name: "Argério Queiroz",
          whatsapp: "(96) 9 8623-3232",
          document: "94482749384",
          key_pix: "3445455ergfer34341",
          email: "teste@toNestErrors.com",
          city: "Macapá",
          training_course: "Engenahria da Computação",
          indicator_id: 2,
          indicator: {
            name: "Damiles Arruda",
            curso: {
              name: "Arquitetura",
            },
          },
          status: "Consultor entrou em contato",
          created_at: "2024-11-02",
          updated_at: "2024-11-02",
        },
      ],
    },
  ],
  leads: [
    {
      id: 6,
      name: "Argério Queiroz",
      whatsapp: "(96) 9 8623-3232",
      document: "94482749384",
      key_pix: "3445455ergfer34341",
      email: "teste@toNestErrors.com",
      city: "Macapá",
      training_course: "Engenahria da Computação",
      indicator_id: 2,
      indicator: {
        name: "Damiles Arruda",
        curso: {
          name: "Arquitetura",
        },
      },
      status: "Consultor entrou em contato",
      created_at: "2024-11-02",
      updated_at: "2024-11-02",
      time_line: [
        {
          id: 1,
          lead_id: 2,
          course_id: 2,
          title: "titulo",
          describe:
            "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
          status: "Matrícula Confirmada",
          created_at: "2023-05-12",
        },
        {
          id: 2,
          lead_id: 2,
          course_id: 2,
          title: "titulo",
          describe:
            "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
          status: "Matrícula Confirmada",
          created_at: "2023-05-12",
        },
        {
          id: 3,
          lead_id: 2,
          course_id: 2,
          title: "titulo",
          describe:
            "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
          status: "Matrícula Confirmada",
          created_at: "2023-05-12",
        },
      ],
    },
    {
      id: 7,
      name: "Argério Queiroz",
      whatsapp: "(96) 9 8623-3232",
      document: "94482749384",
      key_pix: "3445455ergfer34341",
      email: "teste@toNestErrors.com",
      city: "Macapá",
      training_course: "Engenahria da Computação",
      indicator_id: 2,
      indicator: {
        name: "Damiles Arruda",
        curso: {
          name: "Arquitetura",
        },
      },
      status: "Consultor entrou em contato",
      created_at: "2024-11-02",
      updated_at: "2024-11-02",
      time_line: [
        {
          id: 1,
          lead_id: 2,
          course_id: 2,
          title: "titulo",
          describe:
            "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
          status: "Matrícula Confirmada",
          created_at: "2023-05-12",
        },
        {
          id: 2,
          lead_id: 2,
          course_id: 2,
          title: "titulo",
          describe:
            "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
          status: "Matrícula Confirmada",
          created_at: "2023-05-12",
        },
        {
          id: 3,
          lead_id: 2,
          course_id: 2,
          title: "titulo",
          describe:
            "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
          status: "Matrícula Confirmada",
          created_at: "2023-05-12",
        },
      ],
    },
    {
      id: 8,
      name: "Argério Queiroz",
      whatsapp: "(96) 9 8623-3232",
      document: "94482749384",
      key_pix: "3445455ergfer34341",
      email: "teste@toNestErrors.com",
      city: "Macapá",
      training_course: "Engenahria da Computação",
      indicator_id: 2,
      indicator: {
        name: "Damiles Arruda",
        curso: {
          name: "Arquitetura",
        },
      },
      status: "Consultor entrou em contato",
      created_at: "2024-11-02",
      updated_at: "2024-11-02",
      time_line: [
        {
          id: 1,
          lead_id: 2,
          course_id: 2,
          title: "titulo",
          describe:
            "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
          status: "Matrícula Confirmada",
          created_at: "2023-05-12",
        },
        {
          id: 2,
          lead_id: 2,
          course_id: 2,
          title: "titulo",
          describe:
            "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
          status: "Matrícula Confirmada",
          created_at: "2023-05-12",
        },
        {
          id: 3,
          lead_id: 2,
          course_id: 2,
          title: "titulo",
          describe:
            "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
          status: "Matrícula Confirmada",
          created_at: "2023-05-12",
        },
      ],
    },
  ],
  users: [
    {
      id: 1,
      name: "Argério Queiroz",
      email: "argerioaf@gmail.com",
      number: "(96) 9 8623-3232",
      status: 1,
      image:
        "https://img.myloview.com.br/adesivos/humano-homem-pessoa-avatar-perfil-do-usuario-vector-icon-ilustracao-700-80949473.jpg",
      last_name: "Queiroz",
      whatsapp: "123432423324",
      document: "24223423423444",
      datebirth: "2012-12-12",
      genero: 1,
      nivel: 1,
      created_at: "2012-12-12",
    },
    {
      id: 2,
      name: "Argério Queiroz",
      email: "argerioaf@gmail.com",
      number: "(96) 9 8623-3232",
      status: 1,
      image:
        "https://img.myloview.com.br/adesivos/humano-homem-pessoa-avatar-perfil-do-usuario-vector-icon-ilustracao-700-80949473.jpg",
      last_name: "Queiroz",
      whatsapp: "123432423324",
      document: "24223423423444",
      datebirth: "2012-12-12",
      genero: 1,
      nivel: 1,
      created_at: "2012-12-12",
    },
    {
      id: 3,
      name: "Argério Queiroz",
      email: "argerioaf@gmail.com",
      number: "(96) 9 8623-3232",
      status: 1,
      image:
        "https://img.myloview.com.br/adesivos/humano-homem-pessoa-avatar-perfil-do-usuario-vector-icon-ilustracao-700-80949473.jpg",
      last_name: "Queiroz",
      whatsapp: "123432423324",
      document: "24223423423444",
      datebirth: "2012-12-12",
      genero: 1,
      nivel: 1,
      created_at: "2012-12-12",
    },
    {
      id: 4,
      name: "Argério Queiroz",
      email: "argerioaf@gmail.com",
      number: "(96) 9 8623-3232",
      status: 1,
      image:
        "https://img.myloview.com.br/adesivos/humano-homem-pessoa-avatar-perfil-do-usuario-vector-icon-ilustracao-700-80949473.jpg",
      last_name: "Queiroz",
      whatsapp: "123432423324",
      document: "24223423423444",
      datebirth: "2012-12-12",
      genero: 1,
      nivel: 1,
      created_at: "2012-12-12",
    },
    {
      id: 5,
      name: "Argério Queiroz",
      email: "argerioaf@gmail.com",
      number: "(96) 9 8623-3232",
      status: 1,
      image:
        "https://img.myloview.com.br/adesivos/humano-homem-pessoa-avatar-perfil-do-usuario-vector-icon-ilustracao-700-80949473.jpg",
      last_name: "Queiroz",
      whatsapp: "123432423324",
      document: "24223423423444",
      datebirth: "2012-12-12",
      genero: 1,
      nivel: 1,
      created_at: "2012-12-12",
    },
    {
      id: 6,
      name: "Argério Queiroz",
      email: "argerioaf@gmail.com",
      number: "(96) 9 8623-3232",
      status: 1,
      image:
        "https://img.myloview.com.br/adesivos/humano-homem-pessoa-avatar-perfil-do-usuario-vector-icon-ilustracao-700-80949473.jpg",
      last_name: "Queiroz",
      whatsapp: "123432423324",
      document: "24223423423444",
      datebirth: "2012-12-12",
      genero: 1,
      nivel: 1,
      created_at: "2012-12-12",
    },
    {
      id: 7,
      name: "Argério Queiroz",
      email: "argerioaf@gmail.com",
      number: "(96) 9 8623-3232",
      status: 1,
      image:
        "https://img.myloview.com.br/adesivos/humano-homem-pessoa-avatar-perfil-do-usuario-vector-icon-ilustracao-700-80949473.jpg",
      last_name: "Queiroz",
      whatsapp: "123432423324",
      document: "24223423423444",
      datebirth: "2012-12-12",
      genero: 1,
      nivel: 1,
      created_at: "2012-12-12",
    },
  ],
  segments: [
    {
      id: 1,
      name: "EAD",
      created_at: "2012-12-12",
    },
    {
      id: 2,
      name: "EDUCAÇÃO BÁSICA",
      created_at: "2012-12-12",
    },
    {
      id: 3,
      name: "GRADUAÇÃO",
      created_at: "2012-12-12",
    },
    {
      id: 4,
      name: "OUTRAS LOCALIDADES",
      created_at: "2012-12-12",
    },
    {
      id: 5,
      name: "OUTRAS LOCALIDADES",
      created_at: "2012-12-12",
    },
  ],
  unidades: [
    {
      id: 1,
      name: "SANTANA",
      created_at: "19/09/2023",
      segments: [
        {
          id: 1,
          name: "EAD-SANTANA",
          created_at: "19/09/2023",
        },
      ],
      courses: [
        {
          id: 1,
          name: "Pedagogia",
          quant_leads: 2,
          status: 1,
        },
        {
          id: 2,
          name: "Pedagogia",
          quant_leads: 2,
          status: 1,
        },
        {
          id: 3,
          name: "Pedagogia",
          quant_leads: 2,
          status: 1,
        },
        {
          id: 4,
          name: "Pedagogia",
          quant_leads: 2,
          status: 1,
        },
      ],
    },
    {
      id: 2,
      name: "SANTANA 2",
      created_at: "19/09/2023",
      segments: [
        {
          id: 1,
          name: "EAD-SANTANA",
          created_at: "19/09/2023",
        },
        {
          id: 2,
          name: "EAD-SANTANA 2",
          created_at: "19/09/2023",
        },
      ],
      courses: [
        {
          id: 1,
          name: "Pedagogia",
          quant_leads: 2,
          status: 1,
        },
        {
          id: 2,
          name: "Pedagogia",
          quant_leads: 2,
          status: 1,
        },
        {
          id: 3,
          name: "Pedagogia",
          quant_leads: 2,
          status: 1,
        },
        {
          id: 4,
          name: "Pedagogia",
          quant_leads: 2,
          status: 1,
        },
      ],
    },
  ],
  cursos: [
    {
      id: 1,
      name: "Curso 1",
      quant_leads: 2,
      status: 1,
    },
    {
      id: 2,
      name: "Curso 2",
      quant_leads: 2,
      status: 1,
    },
    {
      id: 3,
      name: "Curso 3",
      quant_leads: 4,
      status: 1,
    },
    {
      id: 4,
      name: "Curso 4",
      quant_leads: 3,
      status: 1,
    },
    {
      id: 5,
      name: "Curso 5",
      quant_leads: 6,
      status: 1,
    },
  ],
  time_line: [
    {
      id: 1,
      lead_id: 2,
      course_id: 2,
      title: "titulo",
      describe:
        "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
      status: "Matrícula Confirmada",
      created_at: "2023-05-12",
    },
    {
      id: 2,
      lead_id: 2,
      course_id: 2,
      title: "titulo",
      describe:
        "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
      status: "Matrícula Confirmada",
      created_at: "2023-05-12",
    },
    {
      id: 3,
      lead_id: 2,
      course_id: 2,
      title: "titulo",
      describe:
        "se cadastrou por curiosidade, não pode pagar um curso com o valor das nossas mensalidades e foi irredutível nas quebras de objeções",
      status: "Matrícula Confirmada",
      created_at: "2023-05-12",
    },
  ],
  //permissoes
  //situacao
  listActionsIndicators: [
    {
      id: 1,
      onclick: () => {},
      icon: "Edit",
      href: "indicators/edit",
      name: "Editar",
    },
    {
      id: 2,
      onclick: () => {},
      icon: "Eye",
      href: "dashboard/indicators/",
      name: "Vizualizar",
    },
    {
      id: 3,
      onclick: () => {},
      icon: "Lock",
      href: "home",
      name: "Desativar",
    },
    {
      id: 4,
      onclick: () => {},
      icon: "Link",
      href: "home",
      name: "Link",
    },
  ],
  listActionsUsers: [
    {
      id: 1,
      onclick: () => {},
      icon: "Edit",
      href: "users/edit",
      name: "Editar",
    },
    {
      id: 2,
      onclick: () => {},
      icon: "Eye",
      href: "dashboard/users/",
      name: "Vizualizar",
    },
    {
      id: 3,
      onclick: () => {},
      icon: "Lock",
      href: "home",
      name: "Desativar",
    },
  ],
  listActionsLeads: [
    {
      id: 1,
      onclick: () => {},
      icon: "Edit",
      href: "leads/edit",
      name: "Editar",
    },
    {
      id: 2,
      onclick: () => {},
      icon: "Eye",
      href: "dashboard/leads/",
      name: "Vizualizar",
    },
  ],
  listActionsNewLeads: [
    {
      id: 1,
      onclick: () => {},
      icon: "HandPointLeft",
      href: "leads/edit",
      name: "Pegar",
    },
  ],
  listActionsConfirmedLeads: [
    {
      id: 1,
      onclick: () => {},
      icon: "Eye",
      href: "dashboard/leads/",
      name: "Visualizar",
    },
  ],
  listActionsWaitingConfirmationLeads: [
    {
      id: 1,
      onclick: () => {},
      icon: "Eye",
      href: "dashboard/leads/",
      name: "Visualizar",
    },
    {
      id: 1,
      onclick: () => {},
      icon: "Edit",
      href: "leads/edit",
      name: "Editar",
    },
    {
      id: 2,
      onclick: () => {},
      icon: "Link",
      href: "leads/confirmed",
      name: "Confirmar matrícula",
    },
  ],
  listActionsUnits: [
    {
      id: 1,
      onclick: () => {},
      icon: "Edit",
      href: "users/edit",
      name: "Editar",
    },
    {
      id: 2,
      onclick: () => {},
      icon: "Eye",
      href: "dashboard/units/",
      name: "Vizualizar",
    },
  ],
  listActionsCourses: [
    {
      id: 1,
      onclick: () => {},
      icon: "Edit",
      href: "dashboard/courses/edit",
      name: "Editar",
    },
    {
      id: 2,
      onclick: () => {},
      icon: "Eye",
      href: "dashboard/courses/",
      name: "Vizualizar",
    },
  ],
  listActionsSegments: [
    {
      id: 1,
      onclick: () => {},
      icon: "Edit",
      href: "dashboard/segments/edit",
      name: "Editar",
    },
    {
      id: 2,
      onclick: () => {},
      icon: "Eye",
      href: "dashboard/segments/",
      name: "Vizualizar",
    },
  ],
};
