name: leads-front-ci-test

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Lint and build application
        run: |
          npm -v
          npm i  
          npm run lint
          npm run build